/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.project_queue;

import java.text.DecimalFormat;

/**
 *
 * @author sereypanha
 */
public class MenuPay extends javax.swing.JFrame {
    private double subtotal=0,tax,ctax=1,tatol, amount;
    DecimalFormat df = new DecimalFormat("##0.0000$");
    DecimalFormat dfr = new DecimalFormat("##0.0000៛");
    public MenuPay() {
        initComponents();
        tbTable.setModel(ProductModel1.getModel());
        for(int i=0;i<ProductModel1.getModel().getRowCount();i++){
            String amount = tbTable.getValueAt(i, 4).toString();
            amount = amount.replace("$","");
            subtotal+=Double.parseDouble(amount);
        }
        subtotal += amount;
        tax=subtotal*ctax/100;
        tatol=subtotal+tax;
        txtSubtotal.setText(df.format(subtotal));
        txtTex.setText(df.format(tax));
        txtTotal.setText(df.format(tatol));
    }
        private int x=0;
    private void SetNumber(String number){
        if(txtCashreceive.getText().equals("")){
            txtCashreceive.setText(number);
        }else{
            txtCashreceive.setText(txtCashreceive.getText()+number);
        }
        x++;
        int index = cbPayment.getSelectedIndex();
        switch (index) {
            case 0 -> {  // riel
                if(x==1){
                    txtCashreceive.setText(txtCashreceive.getText()+"R");
                }else{
                    String a = txtCashreceive.getText();
                    a=a.replace("$", "");
                    txtCashreceive.setText(a+"$");
                }
            }
            case 1 -> {
                if(x==1){
                    txtCashreceive.setText(txtCashreceive.getText()+"$");
                }else{
                String a = txtCashreceive.getText();
                a=a.replace("$","");
                txtCashreceive.setText(a+"$");
                }
            }
        }
    }
    private void PaymentDollar(){
        String cashReceive = txtCashreceive.getText();
        cashReceive = cashReceive.replace("$", "");
        double cashReturnDollor = Double.parseDouble(cashReceive) - tatol;
        double cashReturnReil = cashReturnDollor*4100;
        txtCashreturnDollor.setText(df.format(cashReturnDollor));
        txtCashreturnReil.setText(dfr.format(cashReturnReil));
    }
    private void PaymentReil(){
        String cashReceive = txtCashreceive.getText();
        cashReceive = cashReceive.replace("$", "");
        tatol = tatol*4100;
        double cashReturnReil = Double.parseDouble(cashReceive) - tatol;
        double cashReturnDollor = cashReturnReil/4100;
        txtCashreturnDollor.setText(df.format(cashReturnDollor));
        txtCashreturnReil.setText(dfr.format(cashReturnReil));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnC2 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btnPoint2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTex = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbPayment = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtCashreceive = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCashreturnDollor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCashreturnReil = new javax.swing.JTextField();
        btnPayment2 = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        btnPrint2 = new javax.swing.JButton();
        btnRemove2 = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();
        btnExite2 = new javax.swing.JButton();
        btnExite3 = new javax.swing.JButton();
        btnPayment3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnC3 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btnPoint3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtSubtotal1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtTex1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTotal1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cbPayment1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        txtCashreceive1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtCashreturnDollor1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtCashreturnReil1 = new javax.swing.JTextField();
        btnPayment4 = new javax.swing.JButton();
        btnReset3 = new javax.swing.JButton();
        btnPrint3 = new javax.swing.JButton();
        btnRemove3 = new javax.swing.JButton();
        btnUpdate3 = new javax.swing.JButton();
        btnExite4 = new javax.swing.JButton();
        btnExite5 = new javax.swing.JButton();
        btnPayment5 = new javax.swing.JButton();
        btnPayment6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1426, 717));

        jPanel1.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Bai Jamjuree", 0, 36)); // NOI18N
        jLabel17.setText("Custom   Product");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(540, 20, 287, 45);

        btnC2.setBackground(new java.awt.Color(255, 51, 51));
        btnC2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnC2.setText("C");
        btnC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnC2);
        btnC2.setBounds(260, 330, 80, 40);

        btn21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn21.setText("7");
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn21);
        btn21.setBounds(140, 90, 80, 40);

        btn23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn23.setText("5");
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });
        jPanel1.add(btn23);
        btn23.setBounds(140, 170, 80, 40);

        btn25.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn25.setText("3");
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        jPanel1.add(btn25);
        btn25.setBounds(260, 250, 80, 40);

        btn27.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn27.setText("1");
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });
        jPanel1.add(btn27);
        btn27.setBounds(20, 250, 80, 40);

        btn29.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn29.setText("0");
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });
        jPanel1.add(btn29);
        btn29.setBounds(20, 330, 80, 40);

        btn20.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn20.setText("9");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20);
        btn20.setBounds(260, 90, 80, 40);

        btn22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn22.setText("8");
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn22);
        btn22.setBounds(20, 90, 80, 40);

        btn24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn24.setText("6");
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        jPanel1.add(btn24);
        btn24.setBounds(260, 170, 80, 40);

        btn26.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn26.setText("4");
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });
        jPanel1.add(btn26);
        btn26.setBounds(20, 170, 80, 40);

        btn28.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn28.setText("2");
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });
        jPanel1.add(btn28);
        btn28.setBounds(140, 250, 80, 40);

        btnPoint2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnPoint2.setText(".");
        btnPoint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoint2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPoint2);
        btnPoint2.setBounds(140, 330, 80, 40);

        tbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Price", "Qty", "Acount"
            }
        ));
        jScrollPane4.setViewportView(tbTable);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(410, 90, 970, 300);

        jLabel18.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel18.setText("SubTotal :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(16, 418, 82, 23);

        txtSubtotal.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtSubtotal);
        txtSubtotal.setBounds(110, 410, 190, 40);

        jLabel19.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel19.setText("Tex         :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 510, 80, 23);

        txtTex.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel1.add(txtTex);
        txtTex.setBounds(110, 500, 186, 40);

        jLabel20.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel20.setText("Total      :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 590, 80, 23);

        txtTotal.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel1.add(txtTotal);
        txtTotal.setBounds(110, 580, 186, 40);

        jLabel21.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel21.setText("Payment Method  :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(330, 590, 160, 23);

        cbPayment.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        cbPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Riel", "USD" }));
        jPanel1.add(cbPayment);
        cbPayment.setBounds(510, 580, 202, 33);

        jLabel22.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel22.setText("Cash Receive       :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(150, 680, 160, 20);

        txtCashreceive.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel1.add(txtCashreceive);
        txtCashreceive.setBounds(320, 670, 202, 40);

        jLabel23.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel23.setText("Cash Return  $     :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(330, 418, 160, 30);

        txtCashreturnDollor.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel1.add(txtCashreturnDollor);
        txtCashreturnDollor.setBounds(510, 410, 202, 40);

        jLabel24.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel24.setText("Cash Return Reil  :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(330, 510, 170, 23);

        txtCashreturnReil.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel1.add(txtCashreturnReil);
        txtCashreturnReil.setBounds(510, 500, 202, 40);

        btnPayment2.setBackground(new java.awt.Color(0, 102, 255));
        btnPayment2.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPayment2.setText("Payment");
        btnPayment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayment2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment2);
        btnPayment2.setBounds(1120, 410, 100, 40);

        btnReset2.setBackground(new java.awt.Color(0, 102, 255));
        btnReset2.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset2);
        btnReset2.setBounds(1120, 490, 100, 40);

        btnPrint2.setBackground(new java.awt.Color(0, 102, 255));
        btnPrint2.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPrint2.setText("Print");
        btnPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint2);
        btnPrint2.setBounds(1280, 410, 92, 40);

        btnRemove2.setBackground(new java.awt.Color(0, 102, 255));
        btnRemove2.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnRemove2.setText("Remove");
        btnRemove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove2);
        btnRemove2.setBounds(1120, 580, 100, 40);

        btnUpdate2.setBackground(new java.awt.Color(0, 102, 255));
        btnUpdate2.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnUpdate2.setText("Update");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate2);
        btnUpdate2.setBounds(1280, 490, 92, 40);

        btnExite2.setBackground(new java.awt.Color(255, 102, 102));
        btnExite2.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnExite2.setText("LogOut");
        btnExite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExite2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExite2);
        btnExite2.setBounds(1110, 670, 92, 40);

        btnExite3.setBackground(new java.awt.Color(255, 51, 51));
        btnExite3.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnExite3.setText("Exit");
        btnExite3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExite3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExite3);
        btnExite3.setBounds(1280, 670, 92, 40);

        btnPayment3.setBackground(new java.awt.Color(0, 153, 204));
        btnPayment3.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPayment3.setText("Drink");
        btnPayment3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayment3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment3);
        btnPayment3.setBounds(780, 410, 90, 40);

        jPanel2.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Bai Jamjuree", 0, 36)); // NOI18N
        jLabel25.setText("Custom   Product");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(540, 20, 287, 45);

        btnC3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnC3.setText("C");
        btnC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnC3);
        btnC3.setBounds(260, 330, 80, 40);

        btn30.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn30.setText("7");
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });
        jPanel2.add(btn30);
        btn30.setBounds(140, 90, 80, 40);

        btn31.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn31.setText("5");
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });
        jPanel2.add(btn31);
        btn31.setBounds(140, 170, 80, 40);

        btn32.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn32.setText("3");
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });
        jPanel2.add(btn32);
        btn32.setBounds(260, 250, 80, 40);

        btn33.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn33.setText("1");
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });
        jPanel2.add(btn33);
        btn33.setBounds(20, 250, 80, 40);

        btn34.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn34.setText("0");
        btn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn34ActionPerformed(evt);
            }
        });
        jPanel2.add(btn34);
        btn34.setBounds(20, 330, 80, 40);

        btn35.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn35.setText("9");
        btn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn35ActionPerformed(evt);
            }
        });
        jPanel2.add(btn35);
        btn35.setBounds(260, 90, 80, 40);

        btn36.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn36.setText("8");
        btn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn36ActionPerformed(evt);
            }
        });
        jPanel2.add(btn36);
        btn36.setBounds(20, 90, 80, 40);

        btn37.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn37.setText("6");
        btn37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn37ActionPerformed(evt);
            }
        });
        jPanel2.add(btn37);
        btn37.setBounds(260, 170, 80, 40);

        btn38.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn38.setText("4");
        btn38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn38ActionPerformed(evt);
            }
        });
        jPanel2.add(btn38);
        btn38.setBounds(20, 170, 80, 40);

        btn39.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn39.setText("2");
        btn39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn39ActionPerformed(evt);
            }
        });
        jPanel2.add(btn39);
        btn39.setBounds(140, 250, 80, 40);

        btnPoint3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnPoint3.setText(".");
        btnPoint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoint3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPoint3);
        btnPoint3.setBounds(140, 330, 80, 40);

        tbTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Price", "Qty", "Acount"
            }
        ));
        jScrollPane5.setViewportView(tbTable1);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(410, 90, 970, 300);

        jLabel26.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel26.setText("SubTotal :");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(16, 418, 82, 23);

        txtSubtotal1.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        txtSubtotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotal1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtSubtotal1);
        txtSubtotal1.setBounds(110, 410, 190, 40);

        jLabel27.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel27.setText("Tex         :");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(20, 510, 80, 23);

        txtTex1.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel2.add(txtTex1);
        txtTex1.setBounds(110, 500, 186, 40);

        jLabel28.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel28.setText("Total      :");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(20, 590, 80, 23);

        txtTotal1.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel2.add(txtTotal1);
        txtTotal1.setBounds(110, 580, 186, 40);

        jLabel29.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel29.setText("Payment Method  :");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(330, 590, 160, 23);

        cbPayment1.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        cbPayment1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Riel", "USD" }));
        jPanel2.add(cbPayment1);
        cbPayment1.setBounds(510, 580, 202, 33);

        jLabel30.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel30.setText("Cash Receive       :");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(150, 680, 160, 20);

        txtCashreceive1.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel2.add(txtCashreceive1);
        txtCashreceive1.setBounds(320, 670, 202, 40);

        jLabel31.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel31.setText("Cash Return  $     :");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(330, 418, 160, 30);

        txtCashreturnDollor1.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel2.add(txtCashreturnDollor1);
        txtCashreturnDollor1.setBounds(510, 410, 202, 40);

        jLabel32.setFont(new java.awt.Font("Bai Jamjuree", 0, 18)); // NOI18N
        jLabel32.setText("Cash Return Reil  :");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(330, 510, 170, 23);

        txtCashreturnReil1.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        jPanel2.add(txtCashreturnReil1);
        txtCashreturnReil1.setBounds(510, 500, 202, 40);

        btnPayment4.setBackground(new java.awt.Color(0, 102, 255));
        btnPayment4.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPayment4.setText("Payment");
        btnPayment4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayment4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPayment4);
        btnPayment4.setBounds(1120, 410, 100, 40);

        btnReset3.setBackground(new java.awt.Color(0, 102, 255));
        btnReset3.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnReset3.setText("Reset");
        btnReset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset3);
        btnReset3.setBounds(1120, 490, 100, 40);

        btnPrint3.setBackground(new java.awt.Color(0, 102, 255));
        btnPrint3.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPrint3.setText("Print");
        jPanel2.add(btnPrint3);
        btnPrint3.setBounds(1280, 410, 92, 40);

        btnRemove3.setBackground(new java.awt.Color(0, 102, 255));
        btnRemove3.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnRemove3.setText("Remove");
        jPanel2.add(btnRemove3);
        btnRemove3.setBounds(1120, 580, 100, 40);

        btnUpdate3.setBackground(new java.awt.Color(0, 102, 255));
        btnUpdate3.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnUpdate3.setText("Update");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate3);
        btnUpdate3.setBounds(1280, 490, 92, 40);

        btnExite4.setBackground(new java.awt.Color(255, 102, 102));
        btnExite4.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnExite4.setText("LogOut");
        btnExite4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExite4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnExite4);
        btnExite4.setBounds(1140, 670, 92, 40);

        btnExite5.setBackground(new java.awt.Color(255, 51, 51));
        btnExite5.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnExite5.setText("Exit");
        btnExite5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExite5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnExite5);
        btnExite5.setBounds(1280, 670, 92, 40);

        btnPayment5.setBackground(new java.awt.Color(0, 153, 204));
        btnPayment5.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPayment5.setText("Drink");
        btnPayment5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayment5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPayment5);
        btnPayment5.setBounds(790, 410, 90, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        btnPayment6.setBackground(new java.awt.Color(0, 153, 204));
        btnPayment6.setFont(new java.awt.Font("Bai Jamjuree", 0, 14)); // NOI18N
        btnPayment6.setText("Delivery");
        btnPayment6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayment6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment6);
        btnPayment6.setBounds(940, 410, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
        txtCashreceive.setText("");
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        SetNumber("7");
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        SetNumber("5");
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        SetNumber("3");
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed
        SetNumber("1");
    }//GEN-LAST:event_btn27ActionPerformed

    private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
        SetNumber("0");
    }//GEN-LAST:event_btn29ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        SetNumber("9");
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        SetNumber("8");
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        SetNumber("6");
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed
        SetNumber("4");
    }//GEN-LAST:event_btn26ActionPerformed

    private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed
        SetNumber("2");
    }//GEN-LAST:event_btn28ActionPerformed

    private void btnPoint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoint2ActionPerformed
        if(txtCashreceive.getText().contains(".")==false){
            txtCashreceive.setText(txtCashreceive.getText()+".");
        }
    }//GEN-LAST:event_btnPoint2ActionPerformed

    private void btnPayment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayment2ActionPerformed
        int index = cbPayment.getSelectedIndex();
        switch (index) {
            case 0 -> {
                PaymentDollar();
            }
            case 1 ->{
                PaymentReil();
            }
        }
    }//GEN-LAST:event_btnPayment2ActionPerformed
 
   
    
    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        txtCashreturnDollor.setText("");
        txtSubtotal.setText("");
        txtCashreceive.setText("");
        txtTex.setText("");
        txtTotal.setText("");
        cbPayment.setSelectedIndex(0);
        ProductModel1.getModel().setRowCount(0);
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btnExite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExite2ActionPerformed
        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExite2ActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void btnExite3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExite3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExite3ActionPerformed

    private void btnPayment3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayment3ActionPerformed
        Store st = new Store();
        st.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPayment3ActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn34ActionPerformed

    private void btn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn35ActionPerformed

    private void btn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn36ActionPerformed

    private void btn37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn37ActionPerformed

    private void btn38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn38ActionPerformed

    private void btn39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn39ActionPerformed

    private void btnPoint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoint3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoint3ActionPerformed

    private void txtSubtotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotal1ActionPerformed

    private void btnPayment4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayment4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayment4ActionPerformed

    private void btnReset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset3ActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void btnExite4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExite4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExite4ActionPerformed

    private void btnExite5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExite5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExite5ActionPerformed

    private void btnPayment5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayment5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayment5ActionPerformed

    private void btnPayment6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayment6ActionPerformed
        Delivery dl = new Delivery();
        dl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPayment6ActionPerformed

    private void btnPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrint2ActionPerformed

    private void btnRemove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnExite2;
    private javax.swing.JButton btnExite3;
    private javax.swing.JButton btnExite4;
    private javax.swing.JButton btnExite5;
    private javax.swing.JButton btnPayment2;
    private javax.swing.JButton btnPayment3;
    private javax.swing.JButton btnPayment4;
    private javax.swing.JButton btnPayment5;
    private javax.swing.JButton btnPayment6;
    private javax.swing.JButton btnPoint2;
    private javax.swing.JButton btnPoint3;
    private javax.swing.JButton btnPrint2;
    private javax.swing.JButton btnPrint3;
    private javax.swing.JButton btnRemove2;
    private javax.swing.JButton btnRemove3;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnReset3;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnUpdate3;
    private javax.swing.JComboBox<String> cbPayment;
    private javax.swing.JComboBox<String> cbPayment1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbTable;
    private javax.swing.JTable tbTable1;
    private javax.swing.JTextField txtCashreceive;
    private javax.swing.JTextField txtCashreceive1;
    private javax.swing.JTextField txtCashreturnDollor;
    private javax.swing.JTextField txtCashreturnDollor1;
    private javax.swing.JTextField txtCashreturnReil;
    private javax.swing.JTextField txtCashreturnReil1;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtSubtotal1;
    private javax.swing.JTextField txtTex;
    private javax.swing.JTextField txtTex1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    // End of variables declaration//GEN-END:variables
}
